---
title: "README"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Instructions

The purpose of this project is to demonstrate your ability to collect, work with, and clean a data set.
Review criterialess 

    The submitted data set is tidy.
    The Github repo contains the required scripts.
    GitHub contains a code book that modifies and updates the available codebooks with the data to indicate all the variables and summaries calculated, along with units, and any other relevant information.
    The README that explains the analysis files is clear and understandable.
    The work submitted for this project is the work of the student who submitted it.

Getting and Cleaning Data Course Projectless 

The purpose of this project is to demonstrate your ability to collect, work with, and clean a data set. The goal is to prepare tidy data that can be used for later analysis. You will be graded by your peers on a series of yes/no questions related to the project. You will be required to submit: 1) a tidy data set as described below, 2) a link to a Github repository with your script for performing the analysis, and 3) a code book that describes the variables, the data, and any transformations or work that you performed to clean up the data called CodeBook.md. You should also include a README.md in the repo with your scripts. This repo explains how all of the scripts work and how they are connected.

One of the most exciting areas in all of data science right now is wearable computing - see for example this article . Companies like Fitbit, Nike, and Jawbone Up are racing to develop the most advanced algorithms to attract new users. The data linked to from the course website represent data collected from the accelerometers from the Samsung Galaxy S smartphone. A full description is available at the site where the data was obtained:

http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones

Here are the data for the project:

https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip

You should create one R script called run_analysis.R that does the following.

    Merges the training and the test sets to create one data set.
    Extracts only the measurements on the mean and standard deviation for each measurement.
    Uses descriptive activity names to name the activities in the data set
    Appropriately labels the data set with descriptive variable names.
    From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.

Good luck!

## Other Files

Codebook.rmd - contains descriptive information relating to build of tidy data set

run_analysis.r - script that did all of the build to get to final tidy data set

## Directions

Open and run the R script file called run_analysis.
  In line 7, choose where you want the downloaded files to be stored while running the script.
  
# Overview of script:

 Install packages
 
 Set working directory and confirm the location
 
 Download .zip file and it sets name for the file
 
 Unzip the file
 
 File is unzipped and directory is named 'UCI HAR Dataset'. 
 
 Need to set this new directory and then list all files contained within. Recursive because there are other folders within it.
 
 Per instructions, only analyze the training and test sets.
 
 Merges the training and the test sets to create one data set.
 
 Read all the text files into data sets.
 
 Concatenate the subject list together with row bind
 
 Combine datasets and set key.
 
 Subset the ones of interest
 
 Pull from main data according to subset of important variables relating to mean and st dev
 
 Find activity names
 
 Add activity names to main data sub and then set key
 
 Reshape data set to by subj, act num/nm, feature cd so it will be less variables but more obs
 
 Add feature name to data set
 
 From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.
 
 Outputting summary dataset
 
 Create codebook files
 

# Supporting codebook RMD contains descriptive info on final dataset.

